- type: conditional
    conditions:
      - condition: state
        entity: sensor.chinese_workday_sensor
        state: 'False'
    card:
      type: tile
      entity: sensor.chinese_workday_sensor
      color: green
      show_entity_picture: false
      vertical: false
      hide_state: false
      icon_tap_action:
        action: call-service
        service: homeassistant.update_entity
        target:
          entity_id: sensor.chinese_workday_sensor
      icon: mdi:gamepad-variant-outline
      state_content:
        - state
        - last-changed
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.chinese_workday_sensor
        state_not: 'False'
    card:
      type: tile
      entity: sensor.chinese_workday_sensor
      color: red
      show_entity_picture: false
      vertical: false
      hide_state: false
      icon_tap_action:
        action: call-service
        service: homeassistant.update_entity
        target:
          entity_id: sensor.chinese_workday_sensor
      icon: mdi:briefcase
      state_content:
        - state
        - last-changed
